### ISSUE TITLE
Initial app setup 

### ISSUE THREAD

**Issue by angaither** [DoSomething/rogue#1]
- [x] create a laravel app
 - [x] and mock the phoenix tables
- [x] `reportback`
 - [x] `reportback_items`
 - [x] `reportback_log`
 - [x] `kudos`

I think the only initial thing we want to add to the table, is the `northstar_id`

**Comment by sbsmith86** [comment]
Laravel app created! 85999585f898c19230e94b194dde9d912172084c

**Comment by sbsmith86** [comment]
@angaither just to make sure we need to add `northstar_id` to the `reportback` table, right?

**Comment by sbsmith86** [comment]
@angaither actually i think `northstar_id` should just be `user_id` and then `id` in the user table would be the Northstar Id, similar to how we did it in gladiator.

**Comment by sbsmith86** [comment]
Removed the steps to create the POST endpoint and the step to POST back to phoenix. I broke those steps out into their own issues #10, #11 , #12

**Comment by sbsmith86** [comment]
Gonna close this. See the comment above.
