### ISSUE TITLE
/posts endpoint documentation 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#103]
#### User Story

This is not a feature but I need an issue to track the work and remind myself to do it. 

`/posts` endpoint documentation.

**Comment by chloealee** [comment]
@sbsmith86 I can do this if you'd like to also add the update stuff! LMK either way :)

**Comment by sbsmith86** [comment]
@chloealee go for it!

**Comment by chloealee** [comment]
@sbsmith86 just want to double check - we want to have all the documentation [here](https://github.com/DoSomething/rogue/wiki/API) instead of [here](https://github.com/DoSomething/rogue/tree/master/documentation), right? 

If so, I will update the second link's content with a link to the wiki for the most updated documentation.

**Comment by sbsmith86** [comment]
@chloealee I think we should leave it in the documentation directory in the repo but just like to the documentation in the wiki

**Comment by chloealee** [comment]
@sbsmith86 great! I will add that in #112

**Comment by chloealee** [comment]
@sbsmith86 great! I will add that in #112

**Comment by chloealee** [comment]
@sbsmith86 updated [here](https://github.com/DoSomething/rogue/wiki/API/) - let me know if I should flesh out more! Since these are not `GET` endpoints, I didn't add example responses but let me know if I should be doing this.

**Comment by sbsmith86** [comment]
@chloealee looks good! we don't need to do the example responses cause we will most likely be linking these to the full documentation in the wiki.

**Comment by chloealee** [comment]
ok awesome, I'll close this out then. Thanks @sbsmith86 !
