### ISSUE TITLE
Update photo's caption using /posts endpoint

### ISSUE THREAD

**Issue by chloealee** [DoSomething/rogue#111]
_FEATURE OVERVIEW_
-------------------
#### User Story
When we have the ability to update a specific photo's (reportback item's) caption, the `/posts` endpoint should handle this logic to update the post content. 

#### Additional Information (optional)
Refs #100

**Comment by sbsmith86** [comment]
Caption doesn't live on on the photo anymore and we can update the caption on a post, i believe. closing this.
