### ISSUE TITLE
Change `Kudos` to `Reactions` 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#16]
We are changing `Kudos` to `Reactions` externally and have the opportunity in Rogue to make that change easily, internally. So let's change the `Kudos` table to the `Reactions` table. 

Checklist: 
- [x] Make migration to change table name
- [x] Update `Kudo` Model to `Reaction` model
- [x] Create `reportback_reaction` pivot table. Since a reportback could have many reactions and a reaction can belong to many reportbacks. 

That's all for now.

**Comment by chloealee** [comment]
@sbsmith86 I'm reading more about pivot tables and [this article](http://laraveldaily.com/pivot-tables-and-many-to-many-relationships/) says that the naming convention should be in alphabetical order. I think that `reportback_reaction` makes more sense when you read it but should I make it the `reaction_reportback` pivot table to follow convention?

**Comment by sbsmith86** [comment]
yes, follow convention with `reaction_reportback`. sorry

**Comment by chloealee** [comment]
k cool just wanted to double check in case I mis-understood anything!
