### ISSUE TITLE
Enhance total reaction count query 

### ISSUE THREAD

**Issue by chloealee** [DoSomething/rogue#161]
_BUG_
-------------------
#### Current Behavior
- Currently, we are not using eager loading or Eloquent's `::withCount` when querying for total reaction counts in the [Post Transformer](https://github.com/DoSomething/rogue/blob/master/app/Http/Transformers/PostTransformer.php#L30), which also gets called in `GET /activity`.

#### Desired Behavior
- We want to aggregate this in an efficient way. We're thinking it would be good to create a Model Function in the Post class similar to [this](https://github.com/DoSomething/rogue/pull/150#discussion_r106209658). 

#### Steps to Replicate
- Hit `GET /activity` endpoint while looking at the MySQL log and you can see that many queries are being made, which will get a little crazy for each post in the response! 
- @DFurnes also suggested to update the seed data to make many records (500K+) and then hit the `GET /activity` endpoint to see how long it takes to load. 

#### Why This Matters
- We want to run efficient queries to return data!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to enhance the total reaction count query](https://trello.com/c/0DP4xO70/417-as-a-developer-i-want-to-enhance-the-total-reaction-count-query)

**Comment by sbsmith86** [comment]
closing with https://github.com/DoSomething/rogue/pull/164
