### ISSUE TITLE
Drop photos table

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#169]
Remove the `photos` table entirely and the polymorphic relationship between a `Post` and a `Photo`. 

The `posts` table should be update to be able to store all of the content related to a post.

Post columns:
* url - url will now be a url for all things. Could be a URL to a youtube video, or a spotify playlist, or whatever!
* caption
* type (?)
* signup_id
* northstar_id
* status
* source
* remote_addr
* created_at
* updated_at

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to remove the Photos table and polymorphic relationship between a Post and a Photo](https://trello.com/c/pDxhWQ0X/332-as-a-developer-i-want-to-remove-the-photos-table-and-polymorphic-relationship-between-a-post-and-a-photo)
