### ISSUE TITLE
better way to render react onto page

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#176]
_FEATURE OVERVIEW_
-------------------
#### User Story
We want a better way to render the React onto a page. Currently we check for every single element that react renders into and if the element appears on the page, we render the react. We would like a cleaner way of handling this.

#### Additional Information (optional)
Discussions:
https://github.com/DoSomething/rogue/pull/152#issuecomment-284784711
https://github.com/DoSomething/rogue/pull/175#pullrequestreview-28664858

#### Why This Matters
We don't want it to get out of hand.

#### Current Workaround w/o Feature (if applicable)
Every time we want to put React on a page, we have to see if the needed element is there and then render the React if it is.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔪 As a developer, I want a better way to render react on a page 🔪](https://trello.com/c/RndxXRp2/419-as-a-developer-i-want-a-better-way-to-render-react-on-a-page)

**Comment by sbsmith86** [comment]
closing with https://github.com/DoSomething/rogue/pull/394
