### ISSUE TITLE
FUTURE PROBLEMZ

### ISSUE THREAD

**Issue by angaither** [DoSomething/rogue#2]
- [ ] Review endpoint
- [ ] what is the migration strategy? 
- [ ] how does this work with competitions and the mobile app? (omg)
- [ ] the API needs to either grab info from phoenix or 
- [x] How do we store files?

**Comment by sbsmith86** [comment]
We figured out the file storage thing so checking that off

**Comment by sbsmith86** [comment]
Closing.
