### ISSUE TITLE
Queue failed POST requests to Rogue

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#21]
If a POST request fails to the app, we should queue those requests so we can run them again.

**Comment by ngjo** [comment]
Due date: end of this sprint (sept 9)

**Comment by sbsmith86** [comment]
going to close this out in light of #34 

Instead of rogue queuing failed incoming requests, I think the service making the calls should handle failures gracefully. We will just make sure rogue sends back useful errors. 

rogue, in turn, will queue and handle failed outgoing it request as outline in #34
