### ISSUE TITLE
INBOX: Display bug when user email is too long

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#219]
_BUG_
-------------------
#### Current Behavior
- When a user's email is too long it runs behind the accepted/rejected buttons. 

#### Desired Behavior
- Maybe it should wrap? or maybe the text gets smaller so it could fit? Open to suggestions.

#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/1700409/25052541/5b8e9038-2120-11e7-812b-e5b21c7067d9.png)

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔪🐛 Deal with emails that are too long in the inbox 🐛 🔪](https://trello.com/c/Ianh2MwV/421-deal-with-emails-that-are-too-long-in-the-inbox)

**Comment by sbsmith86** [comment]
I believe this has been fixed. We can create a new pivotal card if we see it again.
