### ISSUE TITLE
Add Authorization API middleware for requests to Rogue

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#236]
_FEATURE OVERVIEW_
-------------------
#### User Story

Add key authorization for `POST` and `DELETE` requests to Rogue. Currently, you can send an API request to rogue without any authorization needed. 

Create an authentication middleware that will determine the request method, either `POST` or `DELETE` and check that there is a `X-DS-Rogue-API-Key` header present that matches some matching key we generate and put in the `.env` like `ROGUE_API_KEY`.

Only let the request continue if the two keys match, if not throw an error.

#### Additional Information (optional)

This is how we handle authorizing requests in Gladiator, but I am open to other ideas. @DFurnes maybe you know some other/better methods? Or does this sound ok to you?

**Comment by DFurnes** [comment]
Yeah, this seems good! In the future, it'd be lovely to use Northstar's access tokens here, but it still requires a little bit of extra work. I'm hoping to revisit DoSomething/northstar#535 sometime soon though, so hopefully not a long wait on that. 😄

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) https://github.com/DoSomething/rogue/issues/236](https://trello.com/c/i9RcUtiq/397-3-https-github-com-dosomething-rogue-issues-236)
