### ISSUE TITLE
Documentation: Explain Rogue-native concepts

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/rogue#246]
_DOCUMENTATION_
-------------------
#### The problem

Normal people don't understand Contests vs Competitions, `approved` vs `accepted`, and other Rogue-internal concepts. Let's document them!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) As a developer, I want to continue building out the Rogue documentation TIME BOX 2 HOURS](https://trello.com/c/osx5pHRq/396-2-as-a-developer-i-want-to-continue-building-out-the-rogue-documentation-time-box-2-hours)

**Comment by sbsmith86** [comment]
@mshmsh5000 we had some of this done on the wiki already, I have flushed it out even more. Let me know if you think it is missing anything or anything is not clear!

https://github.com/DoSomething/rogue/wiki

Contests vs. Competitions is more of a Gladiator concept which we should totally document as well. I can work on that in a separate sprint maybe?

**Comment by mshmsh5000** [comment]
Oh wow, I just mis-posted the Gladiator concepts to this repo 👎  Sorry!

The Rogue wiki looks beautiful. I'll read through more thoroughly. Thanks!
