### ISSUE TITLE
Include tags in api responses

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#249]
_FEATURE OVERVIEW_
-------------------
#### User Story

When tagging is functional, we should update the `/activity` and `/reportbacks` response to include post tags.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to update the Activity and Reportbacks endpoints to include post tags](https://trello.com/c/59LxTGPN/416-as-a-developer-i-want-to-update-the-activity-and-reportbacks-endpoints-to-include-post-tags)
