### ISSUE TITLE
Test to create a post is broken

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#251]
_BUG_
-------------------
#### Current Behavior
I broke it when I removed all the code to send Posts to Phoenix in this PR: https://github.com/DoSomething/rogue/pull/244

This is the error:
```
1) PostApiTest::testCreatingAPost
Exception: These expected jobs were not dispatched: [Rogue\Jobs\SendPostToPhoenix]

/home/vagrant/Sites/rogue/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php:144
/home/vagrant/Sites/rogue/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:123
```

#### Desired Behavior
Remove the code from the test that makes sure the job `SendPostToPhoenix` is dispatched. 

#### Steps to Replicate
Just run the tests!

#### Why This Matters
We want good tests!

**Comment by chloealee** [comment]
sorry @katiecrane ! I should have looked in the Issues first but noticed this while I was submitting a PR and just included a quick fix for it. Probably not best practice so I can also just delete this from my PR if that is better! LMK!

**Comment by katiecrane** [comment]
@chloealee totally cool! I mostly wanted to make sure it wasn't forgotten and to document approx. how to fix it! keep the fix in there 😄
