### ISSUE TITLE
Think about how data lives in the campaign inbox/on inbox items

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#259]
Currently signup information is nested within each post, so if something on the signup changes we have to filter through all the posts and see if they have the `signup_id` that changed, and then make the necessary change on their personal signup data. 

Long story short, if something changes on the signup we would like to be able to change it in just one place.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to have signup data living in the state and post use the signup ID associate w/ it to update quantity](https://trello.com/c/3ST2uIDd/431-as-a-developer-i-want-to-have-signup-data-living-in-the-state-and-post-use-the-signup-id-associate-w-it-to-update-quantity)
