### ISSUE TITLE
Hook up the delete button to /posts DELETE endpoint

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#262]
_FEATURE OVERVIEW_
-------------------
#### User Story
When an admin clicks "delete" the post should be soft-deleted from the database and removed from the page.

#### Additional Information (optional)
Documentation for the endpoint to use is [here](https://github.com/DoSomething/rogue/blob/master/documentation/endpoints/posts.md#posts) (scroll down). 

#### Why This Matters
In case an inappropriate photo is submitted, we need admins to be able to remove it themselves.

#### Current Workaround w/o Feature (if applicable)
They would have to manually hit the endpoint, fun!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) As a developer, I want to connect the delete button to the soft-delete backend work](https://trello.com/c/1xaXYO5z/376-5-as-a-developer-i-want-to-connect-the-delete-button-to-the-soft-delete-backend-work)
