### ISSUE TITLE
Validation errors return 500 instead of 422

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#276]
_BUG_
-------------------
#### Current Behavior
I've tested this locally on the posts and signups endpoint. Validation errors give a `500`.

#### Desired Behavior
Validation errors should give a `422`.

#### Steps to Replicate
Hit /posts or /signups and put a string instead of an integer for the `campaign_id`, or the incorrect type for any other validated field.

#### Why This Matters
We want a `422` because it was a validation error and that is how those are signified, and we would also like a message about what went wrong like `campaign_id must be an integer`.

**Comment by katiecrane** [comment]
I've done some digging on this and found that it does hit the code in Laravel to return a validation error, but somehow doesn't end up returning that.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation error https://github.com/DoSomething/rogue/issues/276](https://trello.com/c/XnYvqbRQ/467-validation-error-https%3A%2F%2Fgithub.com%2Fdosomething%2Frogue%2Fissues%2F276)
