### ISSUE TITLE
Add DELETE /posts/{id} to README (documentation) 

### ISSUE THREAD

**Issue by chloealee** [DoSomething/rogue#283]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a dev, I want the `DELETE /posts/{id}` to be included in the README so anyone who wants to know about all Rogue's endpoints will be informed from that page. 

#### Additional Information (optional)
This information is included in the `posts.md` file but just not on the README index/overview of all endpoints. 

#### Why This Matters
Documentation! 📝

**Comment by sbsmith86** [comment]
This is done.
