### ISSUE TITLE
How the F should we build the dang thing?

### ISSUE THREAD

**Issue by angaither** [DoSomething/rogue#3]
1. put this endpoint on a campaign with very little traffic 
   -  rewrite the gallery logic? or just update the url? 
   - if we do this we need to migrate the activity from the campaign we pick
2.  post activity back to phoenix
   - will we ever move stuff out?
   - we don't have to worry about reviewing reportbacks
   - the api questions (how to include users and campaign info) is a non-issue

**Comment by sbsmith86** [comment]
Thought about this overnight and I think you are right @angaither...to avoid the scope creep dealing with all the impacts of storing everything in this new app, I think we should go with option 2. We can get that up pretty quickly and then be able to spend some time really thinking through all the other stuff . /cc @aaronschachter

**Comment by sbsmith86** [comment]
The THANG has been built. so closing.
