### ISSUE TITLE
Discussion: Optimize pagination query

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#325]
I have been looking into some query optimizations for Rogue. New Relic is reporting [this query](https://rpm.newrelic.com/accounts/108038/applications/24971199/datastores#/overview/MySQL/trace/?id=e899ce9a-6e31-11e7-bb42-0242ac11000b_2066_3706&metric=Datastore%252Fstatement%252FMySQL%252Fposts%252Fselect) as being a pretty heavy MySQL transaction. 

I dug into this recommendation: 
![image](https://user-images.githubusercontent.com/1700409/28635758-b6a697ba-7209-11e7-82c7-fe058671e3d4.png)

It seems we should add more indexes to the `posts` table but this query in particular is querying across all rows, so i'm not sure putting an index across all rows will actually help anything (yes?)

So I was digging into why we had to count across all rows instead of just the primary key, `id`, since we are just doing a count. 

It turns out you should be able to pass the specific columns to count in the `paginate()` method [here](https://github.com/DoSomething/rogue/blob/master/app/Http/Controllers/Traits/TransformsRequests.php#L108)

However, this still doesn't work because there seems to be an issue in core where we don't actually pass the specified columns to [getCountForPagination()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L491) Which is called in the `paginate()` method and is the method that actually creates the heavy query

So my questions for discussion are: 

* Did I find an actual issue in core that I should submit a PR for? 
* Is there something we can do on our end to make this query happy? Should I in fact, index across all columns? Should we write our own pagination query?
* Will specifying just counting `posts.id` work? `id` is a primary key and index on the `posts` table so I think it should help the queries performance, but maybe I am wrong.

**Comment by sbsmith86** [comment]
Also, should be noted that this query is running when the `/reportback` and `/activity` endpoints are hit.

**Comment by DFurnes** [comment]
I'm a little stumped by this one. The performance bottleneck seems to be coming from the `inner join` that we're doing on the `signups` table, but we have indexes on both `signup.id`, `posts.signup_id`, and a foreign key connecting them so not sure how much we can improve.

![screen shot 2017-07-27 at 3 34 25 pm](https://user-images.githubusercontent.com/583202/28689327-433f23ca-72e3-11e7-8a42-7d75ed1391f6.png)

While still not great, switching to ["simple pagination"](https://laravel.com/docs/5.4/pagination#basic-usage) does speed up the query on my local significantly – 8.35s to 0.7s. The downside is that we lose pagination information aside from next/previous links (which old implementations rely on).

**Comment by sbsmith86** [comment]
interesting re: simple pagination. I wonder if we could use that on anything that is hitting the new `/activity` endpoint and leave the old `/reportbacks` one in tact, as apps move off of it we will lighten up the load

**Comment by DFurnes** [comment]
Yeah, I think that's a great idea moving forward. 👍

**Comment by DFurnes** [comment]
Alright, I think I was able to improve this a bit in #329. I'm pretty sure this was expected behavior when counting a `INNER JOIN` query (the join could have affected the total number of results if there was a post without a signup, and so a whole-table join needed to occur before the `COUNT(*)` could be processed).

**Comment by sbsmith86** [comment]
Nice!

**Comment by sbsmith86** [comment]
@DFurnes Seeing some weirdness on rogue-thor that looks related to this query. Here is the full stack trace

```Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'campaign_id' in 'where clause' (SQL: select count(*) as aggregate from `posts` where `status` = accepted and `posts`.`id` not in (289102) and `campaign_id` = 1508 and `status` = accepted and `posts`.`deleted_at` is null) in /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Connection.php:729
Stack trace:
#0 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Connection.php(349): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1596): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1671): Illuminate\Database\Query\Builder->get()
#5 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(491): Illuminate\Database\Query\Builder->getCountForPagination()
#6 /var/www/rogue/releases/20170731144833/app/Http/Controllers/Traits/TransformsRequests.php(108): Illuminate\Database\Eloquent\Builder->paginate(6)
#7 /var/www/rogue/releases/20170731144833/app/Http/Controllers/Api/ReportbackController.php(89): Rogue\Http\Controllers\Controller->paginatedCollection(Object(Illuminate\Database\Eloquent\Builder), Object(Illuminate\Http\Request))
#8 [internal function]: Rogue\Http\Controllers\Api\ReportbackController->index(Object(Illuminate\Http\Request))
#9 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#10 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('index', Array)
#11 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(Rogue\Http\Controllers\Api\ReportbackController), Object(Illuminate\Routing\Route), 'index')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Rogue\Http\Controllers\Api\ReportbackController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#18 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Rogue\\Http\\Cont...', 'index')
#19 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/rogue/releases/20170731144833/app/Http/Middleware/LogReceivedRequest.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Rogue\Http\Middleware\LogReceivedRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/rogue/releases/20170731144833/app/Http/Middleware/AuthenticateApi.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Rogue\Http\Middleware\AuthenticateApi->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/rogue/releases/20170731144833/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /var/www/rogue/releases/20170731144833/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 /var/www/rogue/releases/20170731144833/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))```

**Comment by DFurnes** [comment]
Oh, yep – this seems to have broken filtering by `campaign_id` (which makes sense, since that's only stored on the signup and so we wouldn't be able to do it without the join). I wonder if it makes sense to duplicate that column on the `posts` table?

**Comment by sbsmith86** [comment]
That is fine with me, as long as we can backfill posts with their `campaign_id` and I know we are moving away from runs but would we need `campaign_run_id` as well?

**Comment by sbsmith86** [comment]
@DFurnes could we do a `whereHas` to filter on the signup relationship here instead? Or is that heavy as well?

**Comment by sbsmith86** [comment]
Or actually, could we just constrain the eager load? https://laravel.com/docs/5.4/eloquent-relationships#constraining-eager-loads

**Comment by DFurnes** [comment]
> @DFurnes could we do a whereHas to filter on the signup relationship here instead? Or is that heavy as well?

My understanding is that would still require a `join` on the signups table, although I could be wrong!

> Or actually, could we just constrain the eager load? https://laravel.com/docs/5.4/eloquent-relationships#constraining-eager-loads

I think that's only for constraining which signups we'd eager load (like, get all posts but only load their signup if it's for a certain campaign), whereas we want to limit the posts based on that signup column.

**Comment by sbsmith86** [comment]
@DFurnes hrmmm this is the query I am getting when using `WhereHas()` on the query and then eager loading the signups last. 

```
select *, (select count(*) from `reactions` where `reactions`.`post_id` = `posts`.`id` and `reactions`.`deleted_at` is null) as `reactions_count` from `posts` where `status` = ? and `posts`.`id` not in (?, ?, ?, ?, ?, ?, ?, ?) and exists (select * from `signups` where `posts`.`signup_id` = `signups`.`id` and `campaign_id` = ?) and `posts`.`deleted_at` is null
```

How are you measuring the performance of these?

**Comment by DFurnes** [comment]
For the most part, I've just been eyeballing the response time in Paw. To get the raw SQL being generated and timing information, you can also `dump()` out details from [query events](https://laravel.com/docs/5.4/database#listening-for-query-events).

**Comment by DFurnes** [comment]
I tried swapping out for a `whereHas` on my local and I'm seeing 20s response times (using a Thor database dump). I think that `exists (select * from signups where posts.signup_id = signups.id and campaign_id = ?)` is pretty rough.

**Comment by sbsmith86** [comment]
@DFurnes ah gotcha. I'm using my local DB and response times seem fine but clearly that is not a good dataset to use! I'm totally down for adding the column(s) to the posts table, was just wondering if there is anything we can do in the meantime so that we can deploy to prod (what we have now is breaking thor so I don't want to deploy) and it's sorta a blocker for setting up the `/posts` endpoint because it will do similar filtering. 

Also another shot in the dark, could we filter the returned collection based on the eager loaded signups?

**Comment by DFurnes** [comment]
Gah yeah, I know! 😩 I'm up for reverting #329 to get things back in working order.

> Also another shot in the dark, could we filter the returned collection based on the eager loaded signups?

I think the problem we'd run into there is getting inconsistent numbers per page (similar to the problem we'd run into if filtering on the client-side) – we might end up with a page of 50 that only have 3 campaigns that match the `filter[campaign_id]` query param.

**Comment by DFurnes** [comment]
I've tested out a migration to copy the `campaign_id` column onto posts on my local and it does speed things up significantly. I'm thinking that's probably worth the headache of data duplication (at least until we can figure out a better solution).

**Comment by sbsmith86** [comment]
@DFurnes i'm down to do that! can't hurt to have campaign_id in both places. Once the migration is done, we just have to update the post create logic to also store the campaign_id. Could we revert #329 in the meantime?

**Comment by DFurnes** [comment]
Yep, works for me! I'll do that. 🔙
