### ISSUE TITLE
Always prepend cache keys with a string

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#330]
_BUG(ish?)_
-------------------
#### Current Behavior
The cache is all keyed by integers with no indication of what is what. 

#### Desired Behavior
We should prepend these integers with stuff like `campaign_` to indicate what is cached.

#### Why This Matters
So we know what the item in cache represents and so we don't run into conflicts.

**Comment by sbsmith86** [comment]
what conflicts are we seeing?

**Comment by katiecrane** [comment]
@sbsmith86 no conflicts currently. This came up at all because caching with integer keys doesn't work as expected locally with `CACHE_DRIVER=file`. Stuff was broken for me and @chloealee until we switched to `redis`.

**Comment by sbsmith86** [comment]
Hmm my concern is that the key we are using is the campaign id when we use to resolve collections that are missing campaign objects. If a collection is keyed by `id` and cache collections are keyed by `campaign_{id}` we will have to remember to truncate the key or do some other logic. It seems it would put more work on the dev. We shouldn't be using file cache on any of our environments so we shouldn't have to make it work for file cache.

**Comment by katiecrane** [comment]
@sbsmith86 Maybe this isn't something for the immediate future but I still think we should keep it in mind in case we start caching more things

**Comment by DFurnes** [comment]
I think we should definitely be prepending cache keys with some sort of identifier of what the information is being cached. Otherwise it'd be easy to start caching other numeric items and not realize we were getting conflicts. (That said, also very on-board with using Redis everywhere for closer dev/prod parity and that'd have helped us side-step this 👻!)

**Comment by sbsmith86** [comment]
I understand, and we have a `setPrefix()` method already.

**Comment by sbsmith86** [comment]
This has been done. https://github.com/DoSomething/rogue/pull/374
