### ISSUE TITLE
Not getting expected error when not using right API key

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#333]
_BUG_
-------------------
#### Current Behavior
When trying to hit a route behind the `'auth.api'` middleware and when not using a proper API Key I get:
```
{
    "error": {
        "code": 500,
        "message": "Class 'Rogue\\Http\\Middleware\\UnauthorizedAccessException' not found"
    },
    "debug": {
        "file": "/home/vagrant/Sites/rogue/app/Http/Middleware/AuthenticateApi.php",
        "line": 20
    }
}
```

#### Desired Behavior
I think we want a `401` or `403`.

#### Steps to Replicate
Hit an API endpoint with no API Key.

#### Why This Matters
We want to actually throw a `UnauthorizedAccessException`. I don't think this is a huge deal because if you are getting this, you aren't going to be getting a successful response anyway, but it's still confusing.

**Comment by sbsmith86** [comment]
Closing this and referencing it in the issue to review status codes
