### ISSUE TITLE
Crop and Rotate images 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#61]
_FEATURE OVERVIEW_
-------------------
#### User Story

When a reportback is sent to rogue we should store the original image file and also crop, rotate and store the new file separately. We the need to send that edited image back to phoenix so that nothing breaks on the phoenix side which is expecting cropped images.

#### Why This Matters

The gallery layout is currently based on square images and we don't want to break the gallery on the user facing side.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(6) As a developer, I want to store cropped and original reportbacks in rogue.](https://trello.com/c/ShdIgTFK/104-6-as-a-developer-i-want-to-store-cropped-and-original-reportbacks-in-rogue)
