### ISSUE TITLE
Remove the review_source column from the reportback_items table

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#69]
_FEATURE OVERVIEW_
-------------------
#### User Story

Remove the `review_source` from the `reportback_items` table since we don't need it. 

Confirmed we don't need it in [this Trello card.](https://trello.com/c/vRf4Ulzj/157-1-as-a-developer-i-want-to-check-if-we-can-remove-the-review-source-column)

**Comment by sbsmith86** [comment]
https://trello.com/c/vRf4Ulzj/157-1-as-a-developer-i-want-to-check-if-we-can-remove-the-review-source-column

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) As a developer, I want to check if we can remove the 'review_source' column.](https://trello.com/c/vRf4Ulzj/157-1-as-a-developer-i-want-to-check-if-we-can-remove-the-review-source-column)
