### ISSUE TITLE
Campaign showing up as "Unknown Campaign" & inbox won't load for some campaigns 

### ISSUE THREAD

**Issue by chloealee** [DoSomething/rogue#770]
_BUG_
-------------------
#### Current Behavior
- On 9/19/18, @ngjo flagged that Staff Voter Registrations (campaign_id: 8208) was showing up with the title "Unknown Campaign" in Rogue. In addition, Rogue reported 4 pending posts (screen shot below has 5 because Tej tried to reportback again).
![screen shot 2018-09-19 at 9 16 49 am](https://user-images.githubusercontent.com/9019452/45755597-e09f1c80-bbec-11e8-876b-d4099a6e359b.png)

- When you push the "Review" button, the page doesn't load with this error:
![screen shot 2018-09-19 at 9 17 17 am](https://user-images.githubusercontent.com/9019452/45755628-f3b1ec80-bbec-11e8-82b7-3e6896695f17.png)

- Initially, we thought that there was no `noun` and `verb` from the campaign. @ngjo then added a `noun` and `verb` and we cleared the cache. However, nothing changed. 
- I then checked the API to confirm that the `noun` and `verb` (and title of the campaign) were properly being returned from the [Ashes API](https://www.dosomething.org/api/v1/campaigns/8208) which Rogue gets the campaign info from. 
- @ngjo also found [another campaign](https://www.dosomething.org/us/node/8141/edit) that didn't have a `noun` or `verb` but was [displaying info properly in Rogue](https://activity.dosomething.org/campaigns/8141/inbox). Because of these two things, and the fact that even the campaign title name wasn't showing up, we can rule out that it is an issue with `noun` and `verb` not being returned. 
- We suspect there are two issues:
  1. campaign inboxes aren’t loading with campaign names
  2. an inbox says there are posts, but you can’t get to them via the `review` button or via the submitter’s page
- and here are some random things that could be causing it based on campaigns that this is happening to:
  1. one of them only has an ashes campaign
  2. two of them have ashes and phoenix campaign pages
  3. of the two that have ashes and phoenix campaign pages, only one has a redirect set up

- I believe it has something to do with the Rogue API because the front end can't seem to load the data. e.g.  the data _is_ in the database for the posts in this campaign (8208) however, when I try to load the endpoint that the frontend does (`api/v3/posts/669239`) I get a `403 "This action is unauthorized."` message. I think it is also something with the Ashes API because it won't load the campaign name or noun data. Tej also confirmed that he can see his reportback and quantity on Ashes:
![screen shot 2018-09-19 at 8 50 09 am](https://user-images.githubusercontent.com/9019452/45756840-ec401280-bbef-11e8-9d6f-6fc72f101067.png)
 

- **Good news, we can confirm that all data is in the Rogue database (signups/posts for these campaigns, which is why the pending count is accurate), even though we cannot access it via Rogue admin or the Rogue API.** 
 
#### Desired Behavior
- If a campaign has a name, it should show up with that in Rogue and you should be able to review. 

#### Steps to Replicate
- Go to https://activity.dosomething.org/campaigns/8208 and see that you can't see the campaign name. 
- Click on "Review" and the page doesn't load. 

#### Why This Matters
- We want Rogue admin to work for all campaigns and show accurate data!

**Comment by ngjo** [comment]
1. On Thor Ashes, I was able to create a campaign (https://thor.dosomething.org/us/campaigns/test-campaign // Campaign ID: 8205 // Campaign Run ID: 8206). I left nearly everything empty on the Drupal page except for things that were required to publish it -- i.e., I didn't fill in the `noun` and `verb` fields
1a. When I went to Rogue QA, the campaign hadn't showed up on the list of campaigns yet, which I think is how it works until someone signs up or reportsback, so not an issue I don't think.
2. Then I went to the campaign page on Incognito and clicked `Sign Up`
3. It pushed me to Northstar QA where I logged into my non-admin account (https://admin-qa.dosomething.org/users/576c02cd469c64493e8b4576)
4. It signed me up for the campaign and I was able to reportback
5. Then I went to Rogue Thor campaigns overview page and it showed up 
![screen shot 2018-09-19 at 10 01 57 am](https://user-images.githubusercontent.com/2658867/45758201-1515d700-bbf3-11e8-9b1e-92f727623d92.png)
6. When you click in, you can see the one post https://activity-qa.dosomething.org/campaigns/8205 and you are able to click `Review` (which Tej couldn't do for the other inboxes) and you can see the post https://activity-qa.dosomething.org/campaigns/8205/inbox and on my signup page https://activity-qa.dosomething.org/signups/9455726

My next step is to do a side by side comparison if there are any differences between Tej's and my campaigns. I'm pretty sure both Tej and myself have the same `admin` role in Aurora.

**Comment by chloealee** [comment]
@ngjo this is SUPER helpful, thanks for doing all this testing and sleuthing! Yes - I just checked and it looks like Tej is an `admin` as well in Aurora. LMK if all is the same between you and Tej's campaigns. If so, I can go through the same process via my admin account to see what is going on! 

On my end, I'm doing more sleuthing in the code to see anything weird!

**Comment by ngjo** [comment]
Ok, so I compared the drupal for https://thor.dosomething.org/us/campaigns/test-campaign and https://www.dosomething.org/us/campaigns/youth-wave-week-action (YWA)-- they are set up exactly the same (backend fields that are filled in are identical just different words, both are only on ashes w/o contentful counterpart, neither have a redirect in place) except:

1. YWA is on Production, Test Campaign is on Thor
2. YWA was set up by Tej on the 18th, Test Campaign was set up by me today
3. The run for Youth Wave of Action includes a `:`

So here's what Rogue Prod looks like -- you can see `Unknown Campaign 8228` that's YWA (I don't think anyone had signed up or RB, so not sure if it showing up there is important to know since Test Campaign didn't show up until I signed up (but maybe I just didn't wait long enough between creating the campaign and signing up for the Test Campaign and it would of showed up anyways).

![screen shot 2018-09-19 at 11 51 43 am](https://user-images.githubusercontent.com/2658867/45765633-73e34c80-bc03-11e8-951b-13e087767d60.png)

I did the exact same thing as when I was testing on Thor:

1. In incognito, went to https://www.dosomething.org/us/campaigns/youth-wave-week-action
2. Clicked `sign up` and logged into my production non-admin account (https://admin.dosomething.org/users/576c02cd469c64493e8b4576)
3. It signed me up and my sign up showed up in Rogue Prod for this campaign (https://activity.dosomething.org/signups/9483651)
4. I reported back and I got the confirmation message on Phoenix but when I refreshed my signup page, you can see that no posts show up
5. You can also see the at name is still `unknown campaign 8228` and there is a post to review, but you can't access it https://activity.dosomething.org/campaigns/8228

**Comment by ngjo** [comment]
@chloealee Should as a next step I create an account on production and see if it works? I can also see if Tej can create one on Thor to see if it works for him there.

**Comment by chloealee** [comment]
@ngjo this is so weird - thank you for doing such thorough testing! So it seems like it is just an issue with this campaign, YWA? 

Also, what do you mean exactly by the below? 

> The run for Youth Wave of Action includes a `:`

**Comment by chloealee** [comment]
Ah I see now - thanks! I thought you mean the run `id` :) 

> And yes! That's what I meant -- because if a campaign I create on Production works...then it must not be related to the different environments? And if Tej can create one on Thor that works, maybe it has to do with his account on production only? Hahahaha...just thinking of ways to eliminate potential causes!

I think that would be great if you two wouldn't mind doing that final test!

**Comment by ngjo** [comment]
Ok, so Tej created an ashes campaign on Thor and I created an ashes campaign on Production:

1. Tej's campaign on ashes exhibited all of the same things that I documented above (didn't show up in Rogue Thor until signing up) https://thor.dosomething.org/us/campaigns/tej-test-campaign
2. Tej signed up and reported back as I did earlier and the signup and post both show up https://activity-qa.dosomething.org/campaigns/8207/inbox (`Tej Test Campaign` and it's showing up on the /campaigns page)
![screen shot 2018-09-19 at 12 38 16 pm](https://user-images.githubusercontent.com/2658867/45767709-ec98d780-bc08-11e8-96d8-30510b80c882.png)
3. You can access the post via Tej's signup page (https://activity-qa.dosomething.org/signups/9455727) or the `Review` link on the Inbox (https://activity-qa.dosomething.org/campaigns/8207)

For me creating the campaign on Production, all of the issues Tej initially reported with his production campaigns is happening to me:

1.  The campaign https://www.dosomething.org/us/campaigns/test-campaign-w-tej was set up exactly like we did on Thor
2. After signing up and reporting back, it shows up like `unknown campaign` in the /campaigns overview page
![screen shot 2018-09-19 at 12 34 16 pm](https://user-images.githubusercontent.com/2658867/45767851-50230500-bc09-11e8-8a26-cba47bd1b801.png)
3. You can't access the post from here https://activity.dosomething.org/campaigns/8232 or the signups page https://activity.dosomething.org/signups/9483875

I noticed another strange thing between Rogue Production and Thor on the user's signup page:

1. Thor you have campaign names here: https://activity-qa.dosomething.org/users/576c02cd469c64493e8b4576
2. Production you don't have campaign names here: https://activity.dosomething.org/users/576c02cd469c64493e8b4576

Also on that Production link https://activity.dosomething.org/users/576c02cd469c64493e8b4576 you can see that there's a post for `8228` but when you click in you can't see it!

**Comment by chloealee** [comment]
Thank you for all of this @ngjo ! This is SO strange!! So it seems like the code is ok but it is something funky with the prod environment...

**Comment by chloealee** [comment]
Glanced at all the config values and Heroku for Rogue prod and all looks ok..

**Comment by ngjo** [comment]
The last few deploys that involve Rogue seem to be the post `type` , `npm update` and `composure update`, and the fastly stuff?

**Comment by chloealee** [comment]
🤔 I don't think any of that should be different from thor versus prod since those updates were also applied to thor. 

@DFurnes can you explain the Fastly consolidation for Rogue prod?

**Comment by chloealee** [comment]
Touched base with Dave on this [in Slack](https://dosomething.slack.com/archives/C0YGXUE01/p1537376906000100) and ruling out the Fastly update as well since he confirmed they're all using the same Fastly configuration now so the environments shouldn't be inconsistent!

**Comment by ngjo** [comment]
Here's another wacky thing, I published a campaign for our partners in Mexico, so Spanish campaign ID and campaign Run ID (https://www.dosomething.org/node/8187/edit/en) and it's showing up in the /campaigns overview! https://activity.dosomething.org/campaigns/8187

![screen shot 2018-09-20 at 9 14 58 am](https://user-images.githubusercontent.com/2658867/45820882-d432c680-bcb5-11e8-9518-8ff94fbef5c4.png)

**Comment by chloealee** [comment]
that is SO strange @ngjo ! I'm really stumped on this... I keep going back to something about permissions/authorization to access the data because the code seems to be fine since things are working in thor and when you uploaded a campaign for our partners in Mexico, everything worked as expected. 

I keep going back to the `403 "This action is unauthorized."` error I'm getting hitting the Rogue API and also not being able to access the campaign title, again, even though the data is all there. 

@DFurnes @katiecrane can you think of anything that updated recently in Northstar or Ashes in production to affect this? I don't think this makes any sense either though bc everything works in thor and thor/prod environments should be the same?

**Comment by katiecrane** [comment]
@chloealee which Rogue environment are you getting the `403` on? I can try and see if I get that too

**Comment by chloealee** [comment]
thanks @katiecrane ! I was trying on prod on `api/v3/posts/670099`

**Comment by katiecrane** [comment]
@chloealee that is working for me on prod! I had to update a couple of things in Paw though - maybe you're missing something in postman?

**Comment by katiecrane** [comment]
@chloealee I am not!

**Comment by chloealee** [comment]
ah ok - thank you for checking @katiecrane !

**Comment by chloealee** [comment]
OMG the `ASHES_URI` was set to THOR in Rogue prod!! I swear I checked these yesterday as one of the first steps - HOW DID I MISS THIS?! 
![screen shot 2018-09-20 at 1 49 57 pm](https://user-images.githubusercontent.com/9019452/45837154-a8770700-bcdc-11e8-83f3-37278579e090.png)

@ngjo everything should work now - closing this ticket!
