### ISSUE TITLE
Move transaction ID logic into global middleware

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#88]
_FEATURE OVERVIEW_
-------------------
#### User Story

Handle logging and incrementing transaction ids in a global middleware so that we doing have to do write that logic in each method handling incoming requests. 

#### Additional Information (optional)

This comes from a suggestion from @DFurnes :

> This feels like something that'd make sense as a (global?) middleware that reads the X-Transaction-Id header on any incoming request and if found it increments it by one, rather than needing to remember to add these lines to each relevant controller and service class.

#### Why This Matters

It will free us up from having to remember to deal with transaction ids each time we are handling requests in the system.

**Comment by chloealee** [comment]
@sbsmith86 not sure if I'm not understanding correctly but I think we have this already (just not global)? https://github.com/DoSomething/rogue/blob/master/app/Http/Middleware/LogReceivedRequest.php

**Comment by sbsmith86** [comment]
@chloealee Oh whoa! yea i think that's the idea...but then why do we have this also https://github.com/DoSomething/rogue/blob/f8904bdf965f2975d6601b0a95624fed1ed2a9b3/app/Http/Controllers/Api/ReportbackController.php#L39

**Comment by chloealee** [comment]
@sbsmith86 great q! So the middleware is just in charge of incrementing the transaction id to log that the request has been received in Rogue. 

The logic in the Reportback Controller increments the transaction id to update the `X-Request-Id` header to send back to Phoenix (and log that it has been sent).

**Comment by sbsmith86** [comment]
@chloealee got it. i guess we can close this out then! I wonder if there is anything we can do to globalize incrementing transaction ids on outgoing requests though.

**Comment by chloealee** [comment]
@sbsmith86 that would be awesome ! I guess this would happen via Gateway since we have this logic built here already? We have the [`ForwardsTransactionIds`](https://github.com/DoSomething/gateway/blob/master/src/ForwardsTransactionIds.php) trait already but thinking it might get a little hairy to add this logic here since it's already incrementing.

Here's how it works now:
1. Phoenix (or API) sends to Rogue (`-0`)
2. Rogue receives the request.
    - In the middleware, the transaction id is incremented and logged that it was received (`-1`)
3. Rogue sends request back to Phoenix.
    - In the Reportback Controller, the transaction id from the [incoming request](https://github.com/DoSomething/rogue/blob/master/app/Http/Controllers/Api/ReportbackController.php#L39) (`-0`) is incremented and the [header is re-set](https://github.com/DoSomething/rogue/blob/master/app/Services/ReportbackService.php#L40) as `-1`.
    - The request is sent back to Phoenix via Gateway where the logic happens to [increment `-1` again](https://github.com/DoSomething/gateway/blob/master/src/ForwardsTransactionIds.php#L16) and [log that the request has been made](https://github.com/DoSomething/gateway/blob/master/src/ForwardsTransactionIds.php#L33) with incremented step, `-2`

**Comment by sbsmith86** [comment]
@chloealee Yea im sure we could do something in gateway. It looks like we increment to `-1` to log that we received it, but then again when we want to send it back. I feel like we should only have to increment the header once and have that persist somewhere so we can grab it when we want to send it back. It's not a high priority thing but would be interesting to talk through...

**Comment by chloealee** [comment]
@sbsmith86 agreed that would make a lot more sense!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔪 As a developer, I want to move transaction ID logic into global middleware 🔪](https://trello.com/c/Yr1Jq27k/424-as-a-developer-i-want-to-move-transaction-id-logic-into-global-middleware)
