### ISSUE TITLE
return 201 for creation

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#98]
_BUG OVERVIEW_
-------------------
[In at least one place](https://github.com/DoSomething/rogue/blob/master/app/Http/Controllers/Api/ReportbackController.php#L49-L57) we have reversed `201` and `200` responses. 

Discussion here:
https://github.com/DoSomething/rogue/pull/97#discussion_r96509503

**Comment by sbsmith86** [comment]
This controller is no longer used. Closing.
