### ISSUE TITLE
type-hint Phoenix on handle method in SendReportbackToPhoenix

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#99]
_BUG_
-------------------
#### Current Behavior
In [SendReportbackToPhoenix.php](https://github.com/DoSomething/rogue/blob/master/app/Jobs/SendReportbackToPhoenix.php#L36) we don't type-hint anything on the `handle` function.

#### Desired Behavior
This:
```
    public function handle(Phoenix $phoenix)
    {
        // Data that every post will have
        $body = [
        ...
    }
```
#### Why This Matters
[Laravel docs:
](https://laravel.com/docs/5.3/queues#class-structure)

>The handle method is called when the job is processed by the queue. Note that we are able to type-hint dependencies on the handle method of the job. The Laravel service container automatically injects these dependencies.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔪🐛 type-hint Phoenix on handle method in SendReportbackToPhoenix 🐛 🔪](https://trello.com/c/rASnkSy4/423-type-hint-phoenix-on-handle-method-in-sendreportbacktophoenix)

**Comment by sbsmith86** [comment]
We aren't doing this anymore.
